### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by moodstubos** [saigontek/dart-vector-tile#1]
Hi there, 
thank you for this package. 

Unfortunately the current implementation of  `VectorTileLayer.fromRaw(..)` does not allow to get a valid value without knowing about the data type.

In order to convert vector data to a json map, I do something like this:

```
Map<String, dynamic> jsonMap = ...

jsonMap[ key] = value.dartBoolValue ?? value.dartDoubleValue ?? value.dartIntValue ?? value.dartStringValue;
```
This is not possible, because e.g. value.dartBoolValue is always "false" even if value type is "string". 

My suggestion for improvement in `vector_tile_layer.dart`:

change
```
static VectorTileLayer fromRaw({@required raw.VectorTile_Layer rawLayer}) {
   List<VectorTileValue> values = rawLayer.values.map((VectorTile_Value value) {
      return VectorTileValue(
        stringValue: value.stringValue,
        floatValue: value.floatValue,
        doubleValue: value.doubleValue,
        intValue: value.intValue,
        uintValue: value.uintValue,
        sintValue: value.sintValue,
        boolValue: value.boolValue,
      );
    }).toList();
   (..)
```
to

```
 static VectorTileLayer fromRaw({@required raw.VectorTile_Layer rawLayer}) {
    List<VectorTileValue> values = rawLayer.values.map((VectorTile_Value value) {
      return VectorTileValue(
        stringValue: value.hasStringValue() ? value.stringValue : null,
        floatValue: value.hasFloatValue() ? value.floatValue : null,
        doubleValue: value.hasDoubleValue() ? value.doubleValue : null,
        intValue: value.hasIntValue() ? value.intValue : null,
        uintValue: value.hasUintValue() ? value.uintValue : null,
        sintValue: value.hasSintValue() ? value.sintValue : null,
        boolValue: value.hasBoolValue() ? value.boolValue : null,
      );
    }).toList();
   (..)
```

**Comment by bahung1221** [comment]
Hi @moodstubos ,
Thanks for your report.

Honestly, we create this package for one of our projects that still is under construction, so this package may contain some issues. if you found any issues, feel free to create a `report` or a `pull request` here, we really appreciate it 🍺 

I fixed this issue based on your suggestion, it was published to [v0.1.6](https://pub.dev/packages/vector_tile). 🍻
