### ISSUE TITLE
Is there a way to set the geometryType to GeometryType.MultiPolygon?

### ISSUE THREAD

**Issue by lunaticcoding** [saigontek/dart-vector-tile#14]
When I decode and encode a .mbtiles file and use it in MBTilesViewer it crashes. The only difference I can spot is that when encoding an empty list with 

```dart
createVectorTileFeature(
                    id: feature['id'],
                    tags: feature['tags'],
                    type: type.toRaw(),
                    geometry: []
                  );
```

Is there a way to manually set the geometry type here? 

With my decoding logic I get
geometry: {type: GeometryType.MultiPolygon, coordinates: []}

But encoding and then decoding the same file I get:
geometry: {type: GeometryType.Polygon, coordinates: [[]]}

Which I think then crashes the other program I am trying to use to view the tile. 

PS: Same with 

```dart
VectorTile_Feature(
  id: feature['id'],
  tags: feature['tags'],
  type: type.toRaw(),
);
```

**Comment by bahung1221** [comment]
Sorry for the late response, can you please give me the re-produce code so I can check it by myself 😄  A sample mbtiles file is great, too.
Many thanks.
